/**
 * Builds the production bundle and configures package dependencies.
 *
 * The functions deploy process uploads whatever's in the functions folder, and
 * the cloud environment is configured by the package.json file. Normal usage is
 * to maintain separate dependencies and package.json from other parts of the
 * code. Since I'm using next.js for the build though, everything uses the main
 * package.json.
 *
 * So this script mixes the main package.json and build outputs into the
 * functions-specific package.json.
 */

const { execSync } = require("child_process")
const { cpSync, writeFileSync } = require("fs")
const { resolve } = require("path")

const paths = {
  serverSource: resolve("./.next/server"),
  serverDest: resolve("./functions/server"),
  dependencies: resolve("./package.json"),
  base: resolve("./functions/package.base.json"),
  full: resolve("./functions/package.json")
}

execSync("npm run build")

cpSync(paths.serverSource, paths.serverDest, { recursive: true, force: true })

const { dependencies } = require(paths.dependencies)
const { "//": _, ...base } = require(paths.base)
const full = { "//": "Autogenerated, do not edit", ...base, dependencies }

writeFileSync(paths.full, JSON.stringify(full, null, 2))
